runtime: nodejs18 # o la versión que estés usando
instance_class: F2 # puedes elegir la clase de instancia que prefieras

handlers:
- url: /.*
  script: auto

env_variables:
  NODE_ENV: 'production'
  PORT: '8080'
